# -*- coding: utf-8 -*-
"""Python Web scrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQjjI__NOUaFKnOFE8Bl5aA0tMln7aGv

***First I'm going to import necessary python libries for the work***
"""

from bs4 import BeautifulSoup
import requests

url = 'https://en.wikipedia.org/wiki/List_of_countries_by_real_GDP_growth_rate'

page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')

soup.find_all('table')

table = soup.find_all('table')[0]

print(table)

countries = table.find_all('th')

print(countries)

gdp_growth = [title.text.strip() for title in countries]
print(gdp_growth)

import pandas as pd

data = pd.DataFrame(columns = gdp_growth)

data

column_data = table.find_all('tr')

for row in column_data[1:]:
  row_Data = row.find_all('td')
  individual_row_Data = [data.text.strip() for data in row_Data]

  print(individual_row_Data)

  length = len(data)
  data.loc[length] = individual_row_Data

data.head(10)

data.to_csv(r'C:\Users\User\Desktop\Countries.csv', index = False)

